# Assume Python 3.10.
target-version = "py310"
# Decrease the maximum line length to 79 characters.
line-length = 300

# pyflakes, pycodestyle, isort
# flake8 YTT, pydocstyle D, pylint PLC
select = ["F", "E", "W", "I001", "YTT", "D", "PLC"]
# select = ["ALL"]

# E501 Line too long
# D102 Missing docstring in public method
# D100 Missing docstring in public module
# E501 Line too long
# D103 Missing docstring in public function
# D101 Missing docstring in public class
# `multi-line-summary-first-line` (D212)
# `one-blank-line-before-class` (D203)
extend-ignore = ["E501", "D100", "D101", "D102", "D103", "D212", "D203"]

exclude = [".venv", "ultrachat-13B-test.py"]